### ISSUE TITLE
Health Check Failing

### ISSUE THREAD

**Issue by thathaneydude** [corelight/terraform-aws-sensor#7]
**Describe the bug**  
After deployment of the software sensor v27.13.1 AMI into the autoscaling group, the current settings for the health check determines the instance to be unhealthy. The autoscaling group is set to a minimum instance size of 1 so the EC2 traffic is still being successfully mirrored albeit to an "unhealthy" sensor. 

**Reproducing the Bug**  
1. Using terraform version 1.5.7
2. With the latest module version 
3. AWS provider version v5.68.0
4. Software Sensor AMI v27.13.1

**Expected Behavior**  
The target group health check should be able to validate the sensor is up and running through the monitoring port via the HTTP request on port 41080 https://github.com/corelight/terraform-aws-sensor/blob/main/load_balancer.tf#L16

**Screenshots**  
![image](https://github.com/user-attachments/assets/14d5b4a0-a6e0-4870-9ad4-390add0b5c9d)

**Any Additional Context**  
N/A

**Comment by retr0h** [comment]
Issue was fixed in #8 and https://github.com/corelight/terraform-config-sensor/pull/9
